### ISSUE TITLE
Add support TeamCity version 9.0!

### ISSUE THREAD

**Issue by BCR69** [allure-framework/allure-teamcity-plugin#19] opened 2015-02-27 14:00 UTC
Add support TeamCity version 9.0, please!

**Comment by vania-pooh** [comment] 2015-02-27 14:27
@BCR69 any exceptions to fix?

**Comment by BCR69** [comment] 2015-02-27 14:30
@vania-pooh http://stackoverflow.com/a/28426697/4546577

**Comment by vania-pooh** [comment] 2015-02-27 16:11
Can't reproduce this.
![screen shot 2015-02-27 at 7 10 33 pm](https://cloud.githubusercontent.com/assets/829320/6416082/78c33152-beb4-11e4-8f0a-615256c802d9.png)

**Comment by vania-pooh** [comment] 2015-02-27 16:19
@BCR69 are you using Windows version of TeamCity? Probably some custom environment? I tested under Ubuntu 14.04.

**Comment by BCR69** [comment] 2015-02-27 17:02
@vania-pooh I'm using Windows version of TC. Do you installed last version of TC? Maybe me by wrong path put this archive of Allure. I'm not unpack the archive, but simply put to .\plugins directory, where TC is installed

**Comment by vania-pooh** [comment] 2015-02-27 17:09
@BCR69  As you can see on the screenshot I used Teamcity 9.0.2. I placed the plugin to the Teamcity configuration folder. Under Linux it's called .BuildServer and is automatically created in user home directory (~/.BuildServer). I just placed zip file in ~/.BuildServer/plugins and restarted the server.

**Comment by BCR69** [comment] 2015-02-27 17:19
@vania-pooh OK, I'll try reinstall TC and Allure plugin and write about result here.

**Comment by baev** [comment] 2015-06-10 11:49
@BCR69 any updates? Can we close this issue?

**Comment by BCR69** [comment] 2015-06-10 11:52
@baev Yes, you can close, Thanks for help!

**Closed** 2015-06-10 11:54 UTC
